= pacman-mirrorup
:toc:
:toc-placement!:

image:https://img.shields.io/github/v/tag/bpetlert/pacman-mirrorup?include_prereleases&label=release&style=flat-square[Release,link=https://github.com/bpetlert/pacman-mirrorup/releases/latest]
image:https://img.shields.io/aur/version/pacman-mirrorup?style=flat-square["AUR: pacman-mirrorup",link=https://aur.archlinux.org/packages/pacman-mirrorup/]
image:https://img.shields.io/github/license/bpetlert/pacman-mirrorup?style=flat-square["License: GPL-3.0-or-later",link=./COPYING]

*pacman-mirrorup* is a program to retrieve the best and latest Pacman mirror list based on user's geography.

toc::[]

*pacman-mirrorup* uses JSON from https://www.archlinux.org/mirrors/status/[Arch Linux's mirror status] as data source.
It applies filters as the following to original data:

. Only active mirror
. HTTP/HTTPS protocol
. Completion at 100 percent
. Age under one hour

To take user's geography into consideration.
All filtered mirrors are tested data transfer rate.
The mirror's score from original data is weighted using transfer rate.
In other words, mirror's score is refined by using user's download speed.
Finally, the best N mirrors are selected.
The best N mirrors can be changed by `--mirror` option, the default is 10.

The total number of synced mirrors to be tested is 100.
This number can be changed by `--max-check` option.
Set it to zero to test all synced mirrors.

To exclude a specific mirror, use `--exclude <A-DOMAIN-NAME>` option.
This command line option can be specified many times.
The excluded mirror list could also be loaded from a file using `--exclude-from <FILE>` option.
Format is one domain name per line.
For example:

.excluded_mirrors.conf
[source,conf]
----
# This is a comment
ban.this.mirror

# This is a comment too
ban.this-mirror.also
----

== Installation

=== Arch Linux

It is available on AUR as https://aur.archlinux.org/packages/pacman-mirrorup/[pacman-mirrorup].
To build and install arch package from GIT source:

[source,console]
$ git clone https://github.com/bpetlert/pacman-mirrorup.git
$ cd pacman-mirrorup
$ makepkg -p PKGBUILD.local
$ pacman -U pacman-mirrorup-xxxx-1-x86_64.pkg.tar

== Usage

=== Run as systemd service

pacman-mirrorup provides systemd timer unit which can be enabled by

[source,console]
$ systemctl enable --now pacman-mirrorup.timer

To change the options of pacman-mirrorup service, run `systemctl edit pacman-mirrorup.service`

./etc/systemd/system/pacman-mirrorup.service.d/override.conf
[source,ini]
----
[Service]
Environment='MIRRORUP_ARGS=--output-file /etc/pacman.d/mirrorlist --threads 10'
----

To show log message higher than waning try set https://docs.rs/env_logger/0.9.0/env_logger/#enabling-logging[RUST_LOG] environment variable. For example:

./etc/systemd/system/pacman-mirrorup.service.d/override.conf
[source,ini]
----
[Service]
Environment='RUST_LOG=pacman_mirrorup=debug'
Environment='MIRRORUP_ARGS=--output-file /etc/pacman.d/mirrorlist --threads 10'
----

To change the options of pacman-mirrorup timer, run `systemctl edit pacman-mirrorup.timer`

./etc/systemd/system/pacman-mirrorup.timer.d/override.conf
[source,ini]
----
[Timer]
OnCalendar=
OnCalendar=daily
----

=== Run as command line

pacman-mirrorup can also be used directly from console.
Without `--output-file` option, pacman-mirrorup will display output on STDOUT.

== License

*link:./COPYING[GNU General Public License v3.0 or later]*
