@_default:
  just --list

exp-1:
  #!/usr/bin/bash

  MIRRORS_FILE=$TMPDIR/mirrors.json

  if ! [[ -f ${MIRRORS_FILE} ]]; then
    wget -qO - https://archlinux.org/mirrors/status/json/ | jq > ${MIRRORS_FILE}
  fi

  jq \
    --raw-output \
    --compact-output \
    '
    .urls
    | sort_by(.score)[]
    | select(.protocol | contains("http"))
    | select(.completion_pct != null and .delay != null and .score != null)
    | {
        completion_pct: .completion_pct|tonumber,
        delay: .delay|tonumber,
        score: .score|tonumber,
        url: .url,
      }
    | select((.completion_pct == 1.0) and (.delay < 3600))
    ' \
    ${MIRRORS_FILE}
